import gymnasium as gym

from . import agents

##
# Register Gym environments.
##

gym.register(
    id="Isaac-nonPrehensile-Franka-v0",
    entry_point=f"{__name__}.env:NonPrehensileEnv",
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": f"{__name__}.env:NonPrehensileEnvCfg",
        "rsl_rl_cfg_entry_point": f"{agents.__name__}.config.rsl_rl_ppo_cfg:NonPrehensilePPORunnerCfg",
    },
)

gym.register(
    id="Isaac-Clutter6D-Franka-v0",
    entry_point=f"{__name__}.clutter_env:Clutter6DEnv",
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": f"{__name__}.clutter_env:Clutter6DEnvCfg",
        "rsl_rl_cfg_entry_point": (
            f"{agents.__name__}.config.rsl_rl_ppo_cfg:Clutter6DPPORunnerCfg"
        ),
    },
)

gym.register(
    id="Isaac-Clutter6D-DAPL-Franka-v0",
    entry_point=f"{__name__}.clutter_env:Clutter6DEnv",
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": f"{__name__}.clutter_env:Clutter6DDAPLEnvCfg",
        "rsl_rl_cfg_entry_point": (
            f"{agents.__name__}.config.rsl_rl_ppo_cfg:Clutter6DDAPLPPORunnerCfg"
        ),
    },
)

gym.register(
    id="Isaac-AffordanceClutter6D-Franka-v0",
    entry_point=f"{__name__}.affordance_env:AffordanceAwareClutterEnv",
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": (
            f"{__name__}.affordance_env:AffordanceAwareClutterEnvCfg"
        ),
        "rsl_rl_cfg_entry_point": (
            f"{agents.__name__}.config.rsl_rl_ppo_cfg:AffordancePPORunnerCfg"
        ),
    },
)


for task_id, config_name, runner_config_name in (
    (
        "Isaac-AffordanceHammer-Pose-Franka-v0",
        "AffordanceHammerPoseEnvCfg",
        "AffordanceProofPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-Pose-Hard-Franka-v0",
        "AffordanceHammerPoseHardEnvCfg",
        "AffordanceHardProofPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-LowClutter-Franka-v0",
        "AffordanceHammerLowClutterEnvCfg",
        "AffordanceProofPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-Approach-Franka-v0",
        "AffordanceHammerApproachEnvCfg",
        "AffordanceProofPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-Approach-Refine-Franka-v0",
        "AffordanceHammerApproachRefineEnvCfg",
        "AffordanceRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-Approach-Scratch-Franka-v0",
        "AffordanceHammerApproachScratchEnvCfg",
        "AffordanceScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-DirectionalClutter-Franka-v0",
        "AffordanceHammerDirectionalClutterEnvCfg",
        "AffordanceProofPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-Soft-Franka-v0",
        "AffordanceHammerTeacherNoClutterSoftEnvCfg",
        "AffordanceTeacherPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-FrozenV7-Soft-Franka-v0",
        "AffordanceHammerTeacherFrozenV7NoClutterSoftEnvCfg",
        "AffordanceTeacherPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-FrozenV7-GoalWrench-Soft-Franka-v0",
        "AffordanceHammerTeacherFrozenV7NoClutterSoftEnvCfg",
        "AffordanceTeacherFrozenV7GoalWrenchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-GoalWrench-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherNoClutterSafetySoftEnvCfg",
        "AffordanceTeacherFrozenV7GoalWrenchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-FrozenV7-GoalWrench-C1-Franka-v0",
        "AffordanceHammerTeacherNoClutterHardEnvCfg",
        "AffordanceTeacherFrozenV7GoalWrenchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-GoalWrench-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherC2SoftEnvCfg",
        "AffordanceTeacherFrozenV7GoalWrenchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-GoalWrench-C2-SafetyRefine-Soft-Franka-v0",
        "AffordanceHammerTeacherC2SoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-GoalWrench-C2-Franka-v0",
        "AffordanceHammerTeacherC2EnvCfg",
        "AffordanceTeacherFrozenV7GoalWrenchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-DAPL-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherDAPLAlignedNoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-DAPL-Progress-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherDAPLProgressNoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-UnifiedProgress-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherUnifiedProgressNoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-UnifiedDistance-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherUnifiedDistanceNoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-DistanceDAPLGoal-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherDistanceDAPLGoalNoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-InitialRelativeDAPLGoal-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherInitialRelativeDAPLGoalNoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-PositiveInitialRelativeDAPLGoal-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherPositiveInitialRelativeDAPLGoalNoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-PositiveInitialRelativeJointGoal-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherPositiveInitialRelativeJointGoalNoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-PositiveInitialRelativeJointGoalAction010-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherPositiveInitialRelativeJointGoalAction010NoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-SignedInitialRelativeJointGoalAction010-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSignedInitialRelativeJointGoalAction010NoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-LeakySignedInitialRelativeJointGoalAction010-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherLeakySignedInitialRelativeJointGoalAction010NoClutterSoftEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-PositiveInitialRelativeJointGoalAction010-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherPositiveInitialRelativeJointGoalAction010NoC1DiagnosticEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-WeightedComponentProgressAction010-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherWeightedComponentProgressAction010NoC1DiagnosticEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-PositiveComponentImprovementAction010-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherPositiveComponentImprovementAction010NoC1DiagnosticEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-ParetoPoseImprovementAction010-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherParetoPoseImprovementAction010NoC1DiagnosticEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-DyWAKeypointPotentialAction010-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherDyWAKeypointPotentialAction010NoC1DiagnosticEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-DyWABBoxFullScaleAction010-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherDyWABBoxFullScaleAction010NoC1DiagnosticEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-DyWAMatchedPotentialsAction010-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherDyWAMatchedPotentialsAction010NoC1DiagnosticEnvCfg",
        "AffordanceTeacherDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-DyWAMatchedPotentialsMultiQuery16Action010-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherDyWAMatchedPotentialsAction010NoC1DiagnosticEnvCfg",
        "AffordanceTeacherMultiQueryDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-DyWAMatchedPotentialsCartesian-NoC1Diagnostic-Franka-v0",
        "AffordanceHammerTeacherDyWAMatchedPotentialsCartesianNoC1DiagnosticEnvCfg",
        "AffordanceTeacherCartesianDAPLProgressPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-GoalSide-Soft-Franka-v0",
        "AffordanceHammerTeacherGoalSideSoftEnvCfg",
        "AffordanceTeacherPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-GoalSide-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherGoalSideSafetySoftEnvCfg",
        "AffordanceTeacherSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-GoalSide-C1-Explore-Soft-Franka-v0",
        "AffordanceHammerTeacherGoalSideExploreSoftEnvCfg",
        "AffordanceTeacherDirectionalSafetyPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-SemanticCorridor-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticCorridorSoftEnvCfg",
        "AffordanceTeacherDirectionalSafetyPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-SemanticCorridorBarrier-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticCorridorBarrierSoftEnvCfg",
        "AffordanceTeacherDirectionalSafetyPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-SemanticGeodesic-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticGeodesicSoftEnvCfg",
        "AffordanceTeacherDirectionalSafetyPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-SemanticGeodesicConservative-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticGeodesicConservativeSoftEnvCfg",
        "AffordanceTeacherGeodesicPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-SemanticVectorField-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticVectorFieldSoftEnvCfg",
        "AffordanceTeacherGeodesicPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-SemanticVectorFieldExplore-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticVectorFieldExploreSoftEnvCfg",
        "AffordanceTeacherVectorFieldPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationVectorField-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticVectorFieldExploreSoftEnvCfg",
        "AffordanceTeacherRelationVectorFieldPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-Relation-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherNoClutterSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationVectorFieldScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticVectorFieldScratchSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationVectorFieldBalancedScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticVectorFieldBalancedScratchSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationVectorFieldCommittedScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticVectorFieldCommittedScratchSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationVectorFieldClearanceBlendScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticVectorFieldClearanceBlendScratchSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationVectorFieldClearanceRecoveryScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticVectorFieldClearanceRecoveryScratchSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationPotentialConsistentRecoveryScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticPotentialConsistentRecoveryScratchSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationPotentialConsistentCalibratedScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherSemanticPotentialConsistentCalibratedScratchSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationLexicographicPotentialScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherLexicographicPotentialScratchSoftEnvCfg",
        "AffordanceTeacherRelationScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationWrenchLexicographicPotentialScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchLexicographicPotentialScratchSoftEnvCfg",
        "AffordanceTeacherRelationWrenchScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationWrenchSeparatedContactGateScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedContactGateScratchSoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationFullSafeContactGateScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherFullSafeContactGateScratchSoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationFullSafeJointPoseCostScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherFullSafeJointPoseCostScratchSoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationFullSafePostContactPoseCostScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherFullSafePostContactPoseCostScratchSoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationFullSafePostContactImprovementScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherFullSafePostContactImprovementScratchSoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationYawCompatiblePostContactImprovementScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherYawCompatiblePostContactImprovementScratchSoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-T0-RelationYawPositivePostContactImprovementScratch-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherYawPositivePostContactImprovementScratchSoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedScratchPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Relation-C1-Franka-v0",
        "AffordanceHammerTeacherNoClutterHardEnvCfg",
        "AffordanceTeacherRelationHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrench-C1-Franka-v0",
        "AffordanceHammerTeacherNoClutterHardEnvCfg",
        "AffordanceTeacherRelationWrenchHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrenchSeparated-C1-Franka-v0",
        "AffordanceHammerTeacherNoClutterHardEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrenchSeparated-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedC2SoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-ProtectedObstacle-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedC2SoftEnvCfg",
        "AffordanceTeacherProtectedObstacleSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-ProtectedObstacleAdapter-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedC2SoftEnvCfg",
        "AffordanceTeacherProtectedObstacleAdapterPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-ProtectedObstacleExplorationAdapter-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedC2SoftEnvCfg",
        "AffordanceTeacherProtectedObstacleExplorationAdapterPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-ProtectedObstacleClearanceProgressAdapter-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedC2ClearanceProgressSoftEnvCfg",
        "AffordanceTeacherProtectedObstacleExplorationAdapterPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-ProtectedObstacleClearanceProgressAdapter-C2-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedC2ClearanceProgressHardEnvCfg",
        "AffordanceTeacherProtectedObstacleAdapterPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-ProtectedObstacleGeodesicProgressAdapter-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedC2GeodesicProgressSoftEnvCfg",
        "AffordanceTeacherProtectedObstacleExplorationAdapterPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrenchSeparated-C3-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedC3SoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrenchSeparated-Combined-Soft-Franka-v0",
        "AffordanceHammerTeacherWrenchSeparatedCombinedSoftEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrenchSeparated-C2-Franka-v0",
        "AffordanceHammerTeacherC2EnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedC2HardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-ProtectedObstacle-C2-Franka-v0",
        "AffordanceHammerTeacherC2EnvCfg",
        "AffordanceTeacherProtectedObstacleC2HardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrenchSeparated-C2-CriticWarmup-Franka-v0",
        "AffordanceHammerTeacherC2EnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedC2CriticWarmupPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrenchSeparated-C3-Franka-v0",
        "AffordanceHammerTeacherC3EnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-RelationWrenchSeparated-Combined-Franka-v0",
        "AffordanceHammerTeacherEnvCfg",
        "AffordanceTeacherRelationWrenchSeparatedHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Relation-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherNoClutterSafetySoftEnvCfg",
        "AffordanceTeacherRelationSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Relation-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherC2SoftEnvCfg",
        "AffordanceTeacherRelationSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Relation-C3-Soft-Franka-v0",
        "AffordanceHammerTeacherC3SoftEnvCfg",
        "AffordanceTeacherRelationSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Relation-Clutter-Soft-Franka-v0",
        "AffordanceHammerTeacherSoftEnvCfg",
        "AffordanceTeacherRelationSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Relation-C2-Franka-v0",
        "AffordanceHammerTeacherC2EnvCfg",
        "AffordanceTeacherRelationHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Relation-C3-Franka-v0",
        "AffordanceHammerTeacherC3EnvCfg",
        "AffordanceTeacherRelationHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Relation-Combined-Franka-v0",
        "AffordanceHammerTeacherEnvCfg",
        "AffordanceTeacherRelationHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-C1-Franka-v0",
        "AffordanceHammerTeacherNoClutterHardEnvCfg",
        "AffordanceTeacherHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-C1-Soft-Franka-v0",
        "AffordanceHammerTeacherNoClutterSafetySoftEnvCfg",
        "AffordanceTeacherSafetyRefinePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Clutter-Soft-Franka-v0",
        "AffordanceHammerTeacherSoftEnvCfg",
        "AffordanceTeacherPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-C2-Soft-Franka-v0",
        "AffordanceHammerTeacherC2SoftEnvCfg",
        "AffordanceTeacherPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-C3-Soft-Franka-v0",
        "AffordanceHammerTeacherC3SoftEnvCfg",
        "AffordanceTeacherPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-C2-Franka-v0",
        "AffordanceHammerTeacherC2EnvCfg",
        "AffordanceTeacherHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-C3-Franka-v0",
        "AffordanceHammerTeacherC3EnvCfg",
        "AffordanceTeacherHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceTeacher-Combined-Franka-v0",
        "AffordanceHammerTeacherEnvCfg",
        "AffordanceTeacherHardPPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-XY-Franka-v0",
        "AffordanceHammerXYEnvCfg",
        "AffordancePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-Yaw-Franka-v0",
        "AffordanceHammerYawEnvCfg",
        "AffordancePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-Avoid-Franka-v0",
        "AffordanceHammerAvoidEnvCfg",
        "AffordancePPORunnerCfg",
    ),
    (
        "Isaac-AffordanceHammer-Clutter-Franka-v0",
        "AffordanceHammerClutterEnvCfg",
        "AffordancePPORunnerCfg",
    ),
):
    gym.register(
        id=task_id,
        entry_point=f"{__name__}.affordance_env:AffordanceAwareClutterEnv",
        disable_env_checker=True,
        kwargs={
            "env_cfg_entry_point": f"{__name__}.affordance_env:{config_name}",
            "rsl_rl_cfg_entry_point": (
                f"{agents.__name__}.config.rsl_rl_ppo_cfg:{runner_config_name}"
            ),
        },
    )
